export const CHANGE_P1_CHARACTER = 'CHANGE_P1_CHARACTER'
export const CHANGE_P2_CHARACTER = 'CHANGE_P2_CHARACTER'
export const CHANGE_SYMBOL = 'CHANGE_SYMBOL'
export const WHOLE_NEW_PLAYER_CHARACTERS = 'WHOLE_NEW_PLAYER_CHARACTERS'
export const UPDATE_CHARACTER = 'UPDATE_CHARACTER'

export const SET_ANIMATION_SETTING = 'SET_ANIMATION_SETTING'
export const RESET_ANIMATION_SETTING = 'RESET_ANIMATION_SETTING'

// multiplayer
export const UPDATE_USERNAME = 'UPDATE_USERNAME'
export const LOBBY_HOSTED = 'LOBBY_HOSTED'
export const JOINED_LOBBY = 'JOINED_LOBBY'
export const LEAVE_LOBBY = 'LEAVE_LOBBY'
export const ERROR_MULTIPLAYER = 'ERROR_MULTIPLAYER'
export const MATCH_FOUND = 'MATCH_FOUND'
export const READY_UP = 'READY_UP'
export const ROUND_OVER = 'ROUND_OVER'
export const OPPOSING_PLAYER_READY_UP = 'OPPOSING_PLAYER_READY_UP'
export const LOCALLY_STORED_DATA_LOADED = 'LOCALLY_STORED_DATA_LOADED'
export const PLAYER_LEFT_GAME = 'PLAYER_LEFT_GAME'

export const TOGGLE_USERNAME_POPUP_TOOLTIP = 'TOGGLE_USERNAME_POPUP_TOOLTIP'
export const CHAR_ANIM_OUT_TRUE = 'CHAR_ANIM_OUT_TRUE'
export const CHAR_ANIM_OUT_FALSE = 'CHAR_ANIM_OUT_FALSE'
// 
export const QUERIED_ALL_AVAILABLE_LOBBIES = 'QUERIED_ALL_AVAILABLE_LOBBIES'

export const CLIENT_TURN = 'CLIENT_TURN'
export const END_CLIENT_TURN = 'END_CLIENT_TURN'
export const TOGGLE_PLAYERS_TURNS = 'TOGGLE_PLAYERS_TURNS'

// game board
export const START_NEW_GAME = 'START_NEW_GAME'
export const STATE_NEW_GAME = 'STATE_NEW_GAME'
export const UPDATE_GAME_BOARD = 'UPDATE_GAME_BOARD'

// mute
export const TOGGLE_MUTE = 'TOGGLE_MUTE'

// localStorage
export const LOAD_LOCALLY_SAVED_MUTE = 'LOAD_LOCALLY_SAVED_MUTE'
export const LOAD_LOCALLY_SAVED_USERNAME = 'LOAD_LOCALLY_SAVED_USERNAME'
export const LOAD_LOCALLY_SAVED_ANIM_SETTINGS = 'LOAD_LOCALLY_SAVED_ANIM_SETTINGS'
export const LOAD_LOCALLY_SAVED_CHARACTERS = 'LOAD_LOCALLY_SAVED_CHARACTERS'