export const CHANGE_P1_CHARACTER = 'CHANGE_P1_CHARACTER'
export const CHANGE_P2_CHARACTER = 'CHANGE_P2_CHARACTER'
export const CHANGE_SYMBOL = 'CHANGE_SYMBOL'
export const WHOLE_NEW_PLAYER_CHARACTERS = 'WHOLE_NEW_PLAYER_CHARACTERS'

//auth
export const SAVE_FETCHED_USER_DATA = 'SAVE_FETCHED_USER_DATA'
export const LOGGED_IN = 'LOGGED_IN'
export const REGISTERED = 'REGISTERED'
export const REST_AUTH_DATA = 'REST_AUTH_DATA'

export const ADD_TO_CONTROLLED_INPUTS = 'ADD_TO_CONTROLLED_INPUTS'
export const RESET_CONTROLLED_INPUTS = 'RESET_CONTROLLED_INPUTS'

export const FETCHED_USER_DATA = 'FETCHED_USER_DATA'

export const SET_ANIMATION_SETTING = 'SET_ANIMATION_SETTING'
export const RESET_ANIMATION_SETTING = 'RESET_ANIMATION_SETTING'